# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWork

	pod 'Firebase/Core'
	
  target 'MyWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyWorkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
